# Generated by Django 2.0 on 2018-09-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='post',
        ),
    ]
